# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Use the locally installed JDK 25
org.gradle.java.installations.paths=D\:/MC/jdk-25
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.5
# Mod Properties
mod_version=1.0.0
maven_group=com.recipe
archives_base_name=get-recipes
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.160.0+26.2
